services:
  redis:
    image: redis:alpine
    networks:
      - backend

  app:
    build: .
    depends_on:
      - redis
    networks:
      - backend

  celery:
    build: .
    command: ["celery", "-A", "network_sniffer.config.xcelery", "worker", "--loglevel=INFO"]
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge