services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      backend:
        ipv4_address: 172.18.0.2

  app:
    build: .
    depends_on:
      - redis
    networks:
      backend:
        ipv4_address: 172.18.0.3

  celery:
    build: .
    command: ["celery", "-A", "network_sniffer.config.xcelery", "worker", "--loglevel=INFO"]
    depends_on:
      - redis
    networks:
      backend:
        ipv4_address: 172.18.0.4

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16